library(readr)
library(dplyr)
## s1
# gorilla
# f key
s1_set1_f_yes <- read_csv("data_raw/s1_raw_sets/s1_set1_f_yes.csv")
s1_set2_f_yes <- read_csv("data_raw/s1_raw_sets/s1_set2_f_yes.csv")
s1_set3_f_yes <- read_csv("data_raw/s1_raw_sets/s1_set3_f_yes.csv")
s1_set4_f_yes <- read_csv("data_raw/s1_raw_sets/s1_set4_f_yes.csv")
s1_set1_col <- colnames(s1_set1_f_yes)
s1_set2_col <- colnames(s1_set2_f_yes)
s1_set3_col <- colnames(s1_set3_f_yes)
s1_set4_col <- colnames(s1_set4_f_yes)
# set diff btw all sets and remove the extra columns
set1_v_set2 <- setdiff(s1_set1_col,s1_set2_col)
set1_v_set3 <- setdiff(s1_set1_col,s1_set3_col)
set1_v_set4 <- setdiff(s1_set1_col,s1_set4_col) 
s1_set1_f_yes <- s1_set1_f_yes %>% select(-all_of(set1_v_set2))  %>% select(-all_of(set1_v_set3)) %>% select(-all_of(set1_v_set4)) 

set2_v_set1 <- setdiff(s1_set2_col,s1_set1_col)
set2_v_set3 <- setdiff(s1_set2_col,s1_set3_col)
set2_v_set4 <- setdiff(s1_set2_col,s1_set4_col)
s1_set2_f_yes <- s1_set2_f_yes %>% select(-all_of(set2_v_set1))  %>% select(-all_of(set2_v_set3)) %>% select(-all_of(set2_v_set4)) 

set3_v_set1 <- setdiff(s1_set3_col,s1_set1_col)
set3_v_set2 <- setdiff(s1_set3_col,s1_set2_col)
set3_v_set4 <- setdiff(s1_set3_col,s1_set4_col)
s1_set3_f_yes <- s1_set3_f_yes %>% select(-all_of(set3_v_set1))  %>% select(-all_of(set3_v_set2)) %>% select(-all_of(set3_v_set4)) 

set4_v_set1 <- setdiff(s1_set4_col,s1_set1_col)
set4_v_set2 <- setdiff(s1_set4_col,s1_set2_col)
set4_v_set3 <- setdiff(s1_set4_col,s1_set3_col)
s1_set4_f_yes <- s1_set4_f_yes %>% select(-all_of(set4_v_set1))  %>% select(-all_of(set4_v_set2)) %>% select(-all_of(set4_v_set3)) 

# combine 
s1_f_yes <- rbind(s1_set1_f_yes,s1_set2_f_yes,s1_set3_f_yes,s1_set4_f_yes)
write.csv(s1_f_yes,"data_raw/s1_raw_data_f_yes.csv",row.names = FALSE)
# j jey
s1_set1_j_yes <- read_csv("data_raw/s1_raw_sets/s1_set1_j_yes.csv")
s1_set2_j_yes <- read_csv("data_raw/s1_raw_sets/s1_set2_j_yes.csv")
s1_set3_j_yes <- read_csv("data_raw/s1_raw_sets/s1_set3_j_yes.csv")
s1_set4_j_yes <- read_csv("data_raw/s1_raw_sets/s1_set4_j_yes.csv")

s1_set1_col <- colnames(s1_set1_j_yes)
s1_set2_col <- colnames(s1_set2_j_yes)
s1_set3_col <- colnames(s1_set3_j_yes)
s1_set4_col <- colnames(s1_set4_j_yes)
set1_v_set2 <- setdiff(s1_set1_col,s1_set2_col)
set1_v_set3 <- setdiff(s1_set1_col,s1_set3_col)
set1_v_set4 <- setdiff(s1_set1_col,s1_set4_col)
set2_v_set1 <- setdiff(s1_set2_col,s1_set1_col)
set2_v_set3 <- setdiff(s1_set2_col,s1_set3_col)
set2_v_set4 <- setdiff(s1_set2_col,s1_set4_col)
set3_v_set1 <- setdiff(s1_set3_col,s1_set1_col)
set3_v_set2 <- setdiff(s1_set3_col,s1_set2_col)
set3_v_set4 <- setdiff(s1_set3_col,s1_set4_col)
set4_v_set1 <- setdiff(s1_set4_col,s1_set1_col)
set4_v_set2 <- setdiff(s1_set4_col,s1_set2_col)
set4_v_set3 <- setdiff(s1_set4_col,s1_set3_col)
s1_set1_j_yes <- s1_set1_j_yes %>% select(-all_of(set1_v_set2))  %>% select(-all_of(set1_v_set3)) %>% select(-all_of(set1_v_set4)) 
s1_set2_j_yes <- s1_set2_j_yes %>% select(-all_of(set2_v_set1))  %>% select(-all_of(set2_v_set3)) %>% select(-all_of(set2_v_set4))
s1_set3_j_yes <- s1_set3_j_yes %>% select(-all_of(set3_v_set1))  %>% select(-all_of(set3_v_set2)) %>% select(-all_of(set3_v_set4))
s1_set4_j_yes <- s1_set4_j_yes %>% select(-all_of(set4_v_set1))  %>% select(-all_of(set4_v_set2)) %>% select(-all_of(set4_v_set3))

# combine 
s1_j_yes <- rbind(s1_set1_j_yes,s1_set2_j_yes,s1_set3_j_yes,s1_set4_j_yes)
write.csv(s1_j_yes,"data_raw/s1_raw_data_j_yes.csv",row.names = FALSE)

# prolific
s1_set1_prolific_raw_demo <- read_csv("data_raw/s1_raw_sets/s1_set1_prolific_raw_demo.csv")
s1_set2_prolific_raw_demo <- read_csv("data_raw/s1_raw_sets/s1_set2_prolific_raw_demo.csv")
s1_set3_prolific_raw_demo <- read_csv("data_raw/s1_raw_sets/s1_set3_prolific_raw_demo.csv")
s1_set4_prolific_raw_demo <- read_csv("data_raw/s1_raw_sets/s1_set4_prolific_raw_demo.csv")

s1_set1_col <- colnames(s1_set1_prolific_raw_demo)
s1_set2_col <- colnames(s1_set2_prolific_raw_demo)
s1_set3_col <- colnames(s1_set3_prolific_raw_demo)
s1_set4_col <- colnames(s1_set4_prolific_raw_demo)
set1_v_set2 <- setdiff(s1_set1_col,s1_set2_col)
set1_v_set3 <- setdiff(s1_set1_col,s1_set3_col)
set1_v_set4 <- setdiff(s1_set1_col,s1_set4_col)
set2_v_set1 <- setdiff(s1_set2_col,s1_set1_col)
set2_v_set3 <- setdiff(s1_set2_col,s1_set3_col)
set2_v_set4 <- setdiff(s1_set2_col,s1_set4_col)
set3_v_set1 <- setdiff(s1_set3_col,s1_set1_col)
set3_v_set2 <- setdiff(s1_set3_col,s1_set2_col)
set3_v_set4 <- setdiff(s1_set3_col,s1_set4_col)
set4_v_set1 <- setdiff(s1_set4_col,s1_set1_col)
set4_v_set2 <- setdiff(s1_set4_col,s1_set2_col)
set4_v_set3 <- setdiff(s1_set4_col,s1_set3_col)
s1_set1_prolific_raw_demo <- s1_set1_prolific_raw_demo %>% select(-all_of(set1_v_set2))  %>% select(-all_of(set1_v_set3)) %>% select(-all_of(set1_v_set4)) 
s1_set2_prolific_raw_demo <- s1_set2_prolific_raw_demo %>% select(-all_of(set2_v_set1))  %>% select(-all_of(set2_v_set3)) %>% select(-all_of(set2_v_set4))
s1_set3_prolific_raw_demo <- s1_set3_prolific_raw_demo %>% select(-all_of(set3_v_set1))  %>% select(-all_of(set3_v_set2)) %>% select(-all_of(set3_v_set4))
s1_set4_prolific_raw_demo <- s1_set4_prolific_raw_demo %>% select(-all_of(set4_v_set1))  %>% select(-all_of(set4_v_set2)) %>% select(-all_of(set4_v_set3))

s1_prolific_raw_demo <- rbind(s1_set1_prolific_raw_demo,s1_set2_prolific_raw_demo,s1_set3_prolific_raw_demo,s1_set4_prolific_raw_demo)
write.csv(s1_prolific_raw_demo,"data_raw/s1_prolific_raw_demo.csv",row.names = FALSE)
## s2 prolific
s2_set1_prolific_raw_demo <- read_csv("data_raw/s2_raw_sets/s2_set1_prolific_raw_demo.csv")
s2_set2_prolific_raw_demo <- read_csv("data_raw/s2_raw_sets/s2_set2_prolific_raw_demo.csv")
s2_set1_col <- colnames(s2_set1_prolific_raw_demo)
s2_set2_col <- colnames(s2_set2_prolific_raw_demo)
s2 <- setdiff(s2_set1_col,s2_set2_col)
s2_rev <- setdiff(s2_set2_col,s2_set1_col)
s2_set2_prolific_raw_demo <- s2_set2_prolific_raw_demo %>% select(-all_of(s2_rev))
s2_prolific_raw_demo <- rbind(s2_set1_prolific_raw_demo,s2_set2_prolific_raw_demo)
write.csv(s2_prolific_raw_demo,"data_raw/s2_prolific_raw_demo.csv",row.names = FALSE)
